#!/usr/bin/env ruby
require "thor"
require "orchparty"

class OrchPartyCommand < Thor
  desc "generate INPUT_FILE OUTPUT_FILE APPLICATION_NAME", "generates a configuration file for an application"
  method_option :generator, :aliases => "-g", default: "docker_compose_v1", :desc => "Which generator to take"
  method_option :aliases => "g"
  def generate(input_file, output_file, application_name)
    generator = options[:generator] || "docker_compose_v1"
    File.write(output_file, Orchparty.send(generator.to_sym, input_file, application_name))
  end
end

OrchPartyCommand.start
